{% set name = "libmongoc" %}
{% set version = "1.19.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-c-driver/releases/download/{{ version }}/mongo-c-driver-{{ version }}.tar.gz
  sha256: 1732251e3f65bc02ce05c04ce34ef2819b154479108df669f0c045486952521d
  patches:
    - fix-static-dep.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - libbson
    - snappy
    - zlib
    - openssl
    - cyrus-sasl

test:
  commands:
    - test -f ${PREFIX}/include/libmongoc-1.0/mongoc/mongoc.h  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libmongoc-1.0.pc         # [unix]
    - test -f ${PREFIX}/lib/libmongoc-1.0${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\libmongoc-1.0\mongoc\mongoc.h (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\mongoc-1.0.lib (exit 1)    # [win]
    - if not exist %LIBRARY_BIN%\mongoc-1.0.dll (exit 1)    # [win]

about:
  home: https://github.com/mongodb/mongo-c-driver
  license: Apache-2.0
  license_file: COPYING
  summary: A high-performance MongoDB driver for C

extra:
  recipe-maintainers:
    - Tobias-Fischer
